[package]
name = "libint-build"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
cmake.workspace = true
flate2.workspace = true
tar.workspace = true
ureq.workspace = true

[lints]
workspace = true
