use std::{env, fs, path::PathBuf, process::Command, str::FromStr};

use semver::Version;

fn feature_enabled(feature: &str) -> bool {
    std::env::var(format!("CARGO_FEATURE_{}", feature.to_uppercase())).is_ok()
}

#[derive(Debug)]
struct LibintFlags {
    pub link: PathBuf,
    pub include: PathBuf,
    pub version: Version,
}

impl Default for LibintFlags {
    fn default() -> Self {
        Self {
            link: PathBuf::default(),
            include: PathBuf::default(),
            version: Version::new(0, 0, 0),
        }
    }
}

#[derive(Debug, thiserror::Error)]
enum LibintError {
    #[error("Failed to invoke CMake")]
    CmakeNotFound,
    #[error("{0}")]
    LibintNotFound(String),
    #[error("invalid include path: {0}")]
    InvalidIncludePath(String),
    #[error("invalid library path: {0}")]
    InvalidLibPath(String),
    #[error("invalid version: {0}")]
    InvalidVersion(#[from] semver::Error),
}

/// CMakeLists.txt probe to find libint information for compilation
const CMAKELISTS_TXT: &str = r#"
# generated by libint-src
cmake_minimum_required(VERSION 3.15)
project(probe)
find_package(Libint2 REQUIRED)

get_target_property(_probe_inc  Libint2::int2 INTERFACE_INCLUDE_DIRECTORIES)
get_target_property(_probe_libs Libint2::int-static IMPORTED_LOCATION_RELEASE)
get_target_property(_probe_version Libint2::int2 Libint2_VERSION)

message(STATUS "PROBE_INCLUDE_DIRS=${_probe_inc}")
message(STATUS "PROBE_LINK_LIBS=${_probe_libs}")
message(STATUS "PROBE_LINK_VERSION=${_probe_version}")
"#;

/// Create CMakeLists.txt to retrieve necessary flags for linking libint.
fn probe() -> Result<LibintFlags, LibintError> {
    // create probe directory
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let probe_dir = out_dir.join("probe");
    fs::create_dir_all(&probe_dir).expect("couldn't create probe directory");
    fs::write(probe_dir.join("CMakeLists.txt"), CMAKELISTS_TXT)
        .expect("couldn't write contents of CMakeLists.txt");

    let build_dir = probe_dir.join("build");
    fs::create_dir_all(&build_dir).unwrap();

    // configure CMake
    let output = Command::new("cmake")
        .arg("-S")
        .arg(&probe_dir)
        .arg("-B")
        .arg(&build_dir)
        .output()
        .map_err(|_| LibintError::CmakeNotFound)?;

    if !output.status.success() {
        return Err(LibintError::LibintNotFound(
            String::from_utf8_lossy(&output.stderr).to_string(),
        ));
    }

    // parse libint flags from stdout
    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut flags = LibintFlags::default();
    for line in stdout.lines() {
        let line = line.trim_start_matches("-- ");
        if let Some(v) = line.strip_prefix("PROBE_INCLUDE_DIRS=") {
            flags.include =
                PathBuf::from_str(v).map_err(|_| LibintError::InvalidIncludePath(v.to_string()))?;
        } else if let Some(v) = line.strip_prefix("PROBE_LINK_LIBS=") {
            flags.link =
                PathBuf::from_str(v).map_err(|_| LibintError::InvalidLibPath(v.to_string()))?;
        } else if let Some(v) = line.strip_prefix("PROBE_LINK_VERSION=") {
            flags.version = v.parse()?;
        }
    }

    Ok(flags)
}

/// Eigen headers are required at compile-time even for a from-source static
/// build: `libint2/engine.h` transitively includes `solidharmonics.h` and
/// `engine.impl.h`, both of which use Eigen, but libint2's own install tree
/// does not bundle Eigen headers.
fn eigen_include_paths() -> Vec<PathBuf> {
    pkg_config::Config::new()
        .probe("eigen3")
        .expect("eigen3 not found via pkg-config")
        .include_paths
}

fn main() {
    // don't do anything when requesting docs
    if std::env::var("DOCS_RS").is_ok() {
        return;
    }

    if feature_enabled("system") {
        // probe libint library
        let flags = match probe() {
            Ok(flags) => flags,
            Err(e) => panic!("{e}"),
        };

        // forward path to lib
        println!("cargo:rustc-link-search=native={}", flags.link.display());

        // Let pkg_config handle all other dependencies normally (Eigen)
        let mut includes = vec![flags.include];
        includes.extend(eigen_include_paths());

        // forward include paths
        let joined = std::env::join_paths(&includes).unwrap();
        println!("cargo:include={}", joined.to_string_lossy());
    } else {
        // define directory in which libint should be cloned
        // tracking `master` HEAD, not a release tag: v2.13.1 has an install bug where the
        // compiled static libs never make it into CMAKE_INSTALL_PREFIX (fixed post-release,
        // not yet in a tagged version - see libint-build/src/download.rs). Revisit once a
        // release ships with the fix.
        let libint_root = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("libint-master");
        // Prevent downloading if the directory already exists.
        // We assume that libint is already cloned.
        if !libint_root.exists() {
            let dir = libint_build::download(&PathBuf::from(std::env::var("OUT_DIR").unwrap()))
                .expect("download failed");
            assert_eq!(libint_root, dir, "Download directory is not as expected");
        }

        // build libint
        let config = libint_build::Configure::default();
        let install_prefix = config.build(libint_root);
        // forward path to lib (libint-build forces CMAKE_INSTALL_LIBDIR=lib)
        println!(
            "cargo:rustc-link-search=native={}",
            install_prefix.join("lib").display()
        );

        // Let pkg_config handle all other dependencies normally (Eigen)
        let mut includes = vec![install_prefix.join("include")];
        includes.extend(eigen_include_paths());

        // forward include paths
        let joined = std::env::join_paths(&includes).unwrap();
        println!("cargo:include={}", joined.to_string_lossy());
    }
}
